-- Book controller (game/book_controller.lua) --
bookController:getBookData("software_book_1").display = "Software: Úvod do algoritmů"
bookController:getBookData("software_book_1").description.text = "Kolekce knih, které představují a vysvětlují různé rozšířené algoritmy."
bookController:getBookData("software_book_2").display = "Software: Pokročilý design systémů"
bookController:getBookData("software_book_2").description.text = "Série knih vysvětlující, jak psát systémy, které spolu efektivně spolupracují"
bookController:getBookData("software_book_3").display = "Software: Údržba velkých projektů"
bookController:getBookData("software_book_3").description.text = "Velká kolekce knih prozkoumávající psaní snadno udržitelného kódu ve velkém produkčním prostředí."

bookController:getBookData("development_book_1").display = "Vývoj: Plánování předem"
bookController:getBookData("development_book_1").description.text = "Kolekce knih vysvětlující, jak s dobrým plánováním minimalizovat množství práce."
bookController:getBookData("development_book_2").display = "Vývoj: Dejte se do kupy"
bookController:getBookData("development_book_2").description.text = "Knihy napsané známým psychlogem. Zabývají se řešením osobních problémů, což může v situacích s nedostatkem času výrazně pomoct."
bookController:getBookData("development_book_3").display = "Vývoj: Management času"
bookController:getBookData("development_book_3").description.text = "Další kolekce knih, která poskytuje rady ohledně efektivní správy volného času."

bookController:getBookData("sound_book_1").display = "Audio: Aestho Electro"
bookController:getBookData("sound_book_1").description.text = "S touto řadou knih v kanceláři bude tvorba skvělých soundtracků jednodušší."
bookController:getBookData("sound_book_2").display = "Audio: Návod na zvuky zbraní"
bookController:getBookData("sound_book_2").description.text = "Tato kolekce, prodávaná také s knihovnou vzorových zvuků, vám pomůže vytvořit realistické zvuky (nejen) střelby."
bookController:getBookData("sound_book_3").display = "Audio: Šelest listů"
bookController:getBookData("sound_book_3").description.text = "Kolekce knih vysvětlující, jak nahrát skvělé ambientní zvuky."

bookController:getBookData("graphics_book_1").display = "Grafika: Lidská anatomie"
bookController:getBookData("graphics_book_1").description.text = "Stickmani stačit nebudou. Ať už bude vaše grafika realistická či stylizovaná, musíte znát proporce lidského těla."
bookController:getBookData("graphics_book_2").display = "Grafika: Barevné palety"
bookController:getBookData("graphics_book_2").description.text = "Kolekce knih zabývající se výběrem správné barevné palety pro jakoukoliv kompozici."
bookController:getBookData("graphics_book_3").display = "Grafika: Pohyb"
bookController:getBookData("graphics_book_3").description.text = "Tyto knihy vás naučí animovat přesvědčivý pohyb snadno a rychle."

bookController:getBookData("concept_book_1").display = "Koncept: Zapište to!"
bookController:getBookData("concept_book_1").description.text = "Tyto knihy vysvětlují základy herního designu a jak pořád neskákat z jednoho návrhu na jiný."
bookController:getBookData("concept_book_2").display = "Koncept: Je to rozbité? Tak to nespravujte."
bookController:getBookData("concept_book_2").description.text = "Jsou zde popsány běžné chyby a věci, na které si dávat pozor."
bookController:getBookData("concept_book_3").display = "Koncept: Improvizace - finále"
bookController:getBookData("concept_book_3").description.text = "Tato kolekce knih vysvětluje důležitost improvizace v herním vývoji."

bookController:getBookData("management_book_1").display = "Management: Vítejte ve studiu"
bookController:getBookData("management_book_1").description.text = "Skvělá kolekce knih zabývající se uváděním nových zaměstnanců do pracovních pozic, což umožňuje ušetřit čas a (ještě lépe) peníze"
bookController:getBookData("management_book_2").display = "Management: Čas jsou peníze"
bookController:getBookData("management_book_2").description.text = "V těchto knihách jsou vysvětleny základy managementu zaměstnanců, což manažerům spravovat jich víc."
bookController:getBookData("management_book_3").display = "Management: Dejte si volno"
bookController:getBookData("management_book_3").description.text = "Tato řada knih vás naučí, kdy na zaměstnance tlačit či netlačit nebo kdy používat crunch."