-- Complex translations (where simple string overrides aren't possible) --
consoleManufacturers:getData("mintmendo").display = "Mintmendo"
consoleManufacturers:getData("hardmacro").display = "HardMacro"
consoleManufacturers:getData("pineapple").display = "Pineapple"
consoleManufacturers:getData("mega").display = "Mega"
consoleManufacturers:getData("cexpi").display = "Cexpi"
consoleManufacturers:getData("agari").display = "Agari"

-- Platforms
    -- Mintmendo
taskTypes:getData("mintmendo_platform_1_support").display = "Podpora pro 'M-EM'"
taskTypes:getData("mintmendo_platform_2_support").display = "Podpora pro 'M-EMS'"
taskTypes:getData("mintmendo_platform_3_support").display = "Podpora pro 'Mintmendo 128'"
taskTypes:getData("mintmendo_platform_4_support").display = "Podpora pro 'E-Cube'"
taskTypes:getData("mintmendo_platform_5_support").display = "Podpora pro 'Voo'"
taskTypes:getData("mintmendo_platform_6_support").display = "Podpora pro 'VooDoo'"
taskTypes:getData("mintmendo_handheld_1_support").display = "Podpora pro 'Play&Go'"
taskTypes:getData("mintmendo_handheld_2_support").display = "Podpora pro 'VirtualWorld'"
taskTypes:getData("mintmendo_handheld_3_support").display = "Podpora pro 'Play&Go 2'"
taskTypes:getData("mintmendo_handheld_4_support").display = "Podpora pro 'Play&Go ES'"
taskTypes:getData("mintmendo_handheld_5_support").display = "Podpora pro 'Play&Go ES 3D'"
taskTypes:getData("mintmendo_handheld_6_support").display = "Podpora pro 'Play&Go SWAP'"
    -- HardMacro
taskTypes:getData("vertice_support").display = "Podpora pro 'Vertice'"
taskTypes:getData("vertice_x_support").display = "Podpora pro 'Vertice X'"
taskTypes:getData("vertice_x2_support").display = "Podpora pro 'Vertice X2'"
platforms:getData("vertice").releaseText = "HardMacro vydal novou konzoli 'Vertice'."
platforms:getData("vertice_x").releaseText = "HardMacro vydal novou konzoli 'Vertice X'."
platforms:getData("vertice_x2").releaseText = "HardMacro vydal novou konzoli 'Vertice X2'."
platforms:getData("vertice").expiryText = "HardMacro oficiálně ukončil podporu pro 'Vertice'."
platforms:getData("vertice_x").expiryText = "HardMacro oficiálně ukončil podporu pro 'Vertice X'."
platforms:getData("vertice_x2").expiryText = "HardMacro oficiálně ukončil podporu pro 'Vertice X2'."
    -- Pineapple
taskTypes:getData("abacaxi_1_support").display = "Podpora pro 'Abacaxi SE'"
taskTypes:getData("abacaxi_2_support").display = "Podpora pro 'Abacaxi III'"
taskTypes:getData("abacaxi_3_support").display = "Podpora pro 'Abacaxi G4'"
taskTypes:getData("abacaxi_4_support").display = "Podpora pro 'Abacaxi G5'"
taskTypes:getData("abacaxi_5_support").display = "Podpora pro 'Abacaxi Pro'"
taskTypes:getData("abacaxi_6_support").display = "Podpora pro 'Abacaxi Master'"
taskTypes:getData("pineapple_phone_1_support").display = "Podpora pro 'pPhone'"
platforms:getData("pineapple_phone_1").releaseText = "Pineapple vydal své nové mobilní zařízení, 'pPhone'. Má dotykovou obrazovku a běží na proprietárním operačním systému 'pOS'. Vzhledem k nízkým specifikacím lze očekávat, že pro zařízení budou vydávány spíše nenáročné hry."
    -- Mega
taskTypes:getData("mega_platform_1_support").display = "Podpora pro 'Mega Origin'"
taskTypes:getData("mega_platform_2_support").display = "Podpora pro 'Mega Jupiter'"
taskTypes:getData("mega_platform_3_support").display = "Podpora pro 'Mega Expand'"
taskTypes:getData("mega_platform_4_support").display = "Podpora pro 'Mega Horizon'"
taskTypes:getData("mega_platform_5_support").display = "Podpora pro 'Mega Beyond'"
taskTypes:getData("mega_platform_6_support").display = "Podpora pro 'Mega Forever'"
platforms:getData("mega_platform_1").releaseText = "Mega vydala novou konzoli 'Origin'."
platforms:getData("mega_platform_2").releaseText = "Mega vydala novou konzoli 'Origin'."
platforms:getData("mega_platform_3").releaseText = "Mega vydala novou konzoli 'Mega Expand'."
platforms:getData("mega_platform_4").releaseText = "Mega vydala novou konzoli 'Mega Horizon'."
platforms:getData("mega_platform_5").releaseText = "Mega vydala novou konzoli 'Mega Beyond'."
platforms:getData("mega_platform_6").releaseText = "Mega vydala novou konzoli 'Mega Forever'."
    -- Agari
taskTypes:getData("agari_platform_1_support").display = "Podpora pro 'HEGHS'"
taskTypes:getData("agari_platform_2_support").display = "Podpora pro 'HEGHS 2.0'"
taskTypes:getData("agari_platform_3_support").display = "Podpora pro 'Puma'"
taskTypes:getData("agari_platform_4_support").display = "Podpora pro 'X.Y.U.'"
taskTypes:getData("agari_platform_5_support").display = "Podpora pro 'Bear'"
taskTypes:getData("agari_platform_6_support").display = "Podpora pro 'Ultra'"
platforms:getData("agari_platform_1").releaseText = "Agari vydalo novou platformu 'HEGHS'."
platforms:getData("agari_platform_2").releaseText = "Agari vydalo novou platformu 'HEGHS 2.0'."
platforms:getData("agari_platform_3").releaseText = "Agari vydalo novou platformu 'PUMA'."
platforms:getData("agari_platform_4").releaseText = "Agari vydalo novou platformu 'X.Y.U'."
platforms:getData("agari_platform_5").releaseText = "Agari vydalo novou platformu 'Bear'."
platforms:getData("agari_platform_6").releaseText = "Agari vydalo novou platformu 'Ultra'."
    -- CEXPI
taskTypes:getData("polystation_1_support").display = "Podpora pro 'Polystation 1'"
-- taskTypes:getData("polystation_1_support").setupDescbox[1] = "Umožní vývoj her pro 'PLATFORM'."
taskTypes:getData("polystation_2_support").display = "Podpora pro 'Polystation 2'"
taskTypes:getData("polystation_3_support").display = "Podpora pro 'Polystation 3'"
taskTypes:getData("polystation_4_support").display = "Podpora pro 'Polystation 4'"
taskTypes:getData("polystation_handheld_1_support").display = "Podpora pro 'Polystation Pocket'"
taskTypes:getData("polystation_handheld_2_support").display = "Podpora pro 'Polystation Pocket 2'"
platforms:getData("polystation_1").releaseText = "C-EXPI vydalo novou konzoli 'Polystation 1'."
platforms:getData("polystation_2").releaseText = "C-EXPI vydalo novou konzoli 'Polystation 2'."
platforms:getData("polystation_3").releaseText = "C-EXPI vydalo novou konzoli 'Polystation 3'."
platforms:getData("polystation_4").releaseText = "C-EXPI vydalo novou konzoli 'Polystation 4'."
platforms:getData("polystation_handheld_1").releaseText = "C-EXPI vydalo nový handheld 'Polystation Pocket'."
platforms:getData("polystation_handheld_2").releaseText = "C-EXPI vydalo nový handheld 'Polystation Pocket 2'."